### ISSUE TITLE
Retaining sessions with Docker Restart

### ISSUE THREAD

**Issue by mehak-sachdeva** [chriswhong/docker-cartodb#1]
This is great - got the environment working but am wondering a way of retaining the session and metadata with each time docker restarts.
Thanks!

**Comment by chriswhong** [comment]
Glad to hear you got it working.  What do you mean by retaining the session?  Are you losing data when docker restarts?

**Comment by mehak-sachdeva** [comment]
Yes, after `docker stop {docker-id}` and subsequent `docker run`, a new container image gets created and does not retain the maps I created in the previous session. I am new to docker too, so I was wondering if I am missing anything.

**Comment by chriswhong** [comment]
I see.  The instance i have had up and running is based on https://github.com/sverhoeven/docker-cartodb, and it does persist data when docker restarts, so it is probably using [docker volumes](https://docs.docker.com/engine/tutorials/dockervolumes/) somehow.  

We will need to modify this dockerfile to use them too.

**Comment by chriswhong** [comment]
I have also considered running the postgresql database in another
container, which might make it easier to upgrade when new versions are
released.  I am not sure how this would work, but would love input if
anyone can help.

**Comment by chriswhong** [comment]
So I spoke too soon, you should be able to use `docker stop {containerid}` and then `docker
start {containerid}`, and the same container will run again with the data intact.

If you are using `docker run`, you are spinning up a new container from the
image, which is basically telling it to start over from scratch.

Use `docker ps -a` and you should see a list of your stopped containers.

**Comment by mehak-sachdeva** [comment]
Oh great. Thanks Chris! Yes, docker run was creating a new container from the image. docker stop {id} and docker start {id} worked but kept exiting until I added docker attach {id} after that too.
Also, I am running this on Mac OS so maybe that differed there a little. 
It works great now. Thanks for all your help!
