### ISSUE TITLE
the port 3000 in jeopardy

### ISSUE THREAD

**Issue by Namec** [chriswhong/docker-cartodb#10]
i have succeeded to install CartoDB with no problem.

but each time a clic on a link, i get a 404 error, because i need each time to add the port 3000 to the URL, to make it work.

any solution ?

let the force be with you

**Comment by christianurich** [comment]
Not sure if this helps but I use the following to start my containers and it runs fine on my localhost as well as in the cloud

```
docker run  --name cartodb1 -d -p 3000:3000 -p 8080:8080 -p 8181:8181 docker cartodb

# Start ngnix in docker and connect to carto container
docker run  -p 80:80 --link cartodb1:cartodb.localhost -d spawnthink/cartodb-nginx
```

Also see https://hub.docker.com/r/spawnthink/cartodb-nginx/

**Comment by Namec** [comment]
great, it works fine,

i have missed that part of the installation process.

let the force be with you

**Comment by chriswhong** [comment]
Closing, glad you got it working
