### ISSUE TITLE
Large Files

### ISSUE THREAD

**Issue by Prindle19** [chriswhong/docker-cartodb#13]
Great image, Chris! Got it up and running on Google Cloud Platform with almost no problems!

However, I am having difficulty uploading large shapefiles. 

The first thing I noticed was that the NGINX proxy conf was set to only permit 100MB uploads, so i changed client_max_body_size to 10000M; 

That got me further, allowing me to upload large zip files. 

But, now i'm running into a new error. The uploader successfully uploads and then unzips, but then the import fails and I get a 6666 error: 

https://github.com/CartoDB/cartodb/issues/3956

**Comment by Prindle19** [comment]
Oh, ok, actually i figured it out. 

There's a max import file size setting in the users table: 

 max_import_file_size           | bigint                      | not null default 157286400
 max_import_table_row_count     | bigint                      | not null default 500000
 max_concurrent_import_count    | integer                     | not null default 3

You can raise the file size and row counts - i'm sure this will impact performance on these non-scaling docker based implementations though.

**Comment by chriswhong** [comment]
I think I found this a long time ago but had forgotten where it was.  Are
you just manually modifying stuff in the databases via psql?

**Comment by Prindle19** [comment]
Yeah, probably incredibly dangerous, but yeah.

**Comment by chriswhong** [comment]
Yeah I have been doing the same, I think there are rake tasks for some of these things.  I haven't broken anything yet just psqling though.
