### ISSUE TITLE
Enable Private Maps

### ISSUE THREAD

**Issue by Prindle19** [chriswhong/docker-cartodb#15]
Request enabling Private (password and private links) Maps. 

This is turned off by default because the hosted version of CartoDB doesn't have this feature, but it's fine to use it in the open source version.

# current = f
UPDATE users SET private_maps_enabled = 't';
 
Recommend altering the table so that new users always get private maps: 

ALTER TABLE users ALTER COLUMN private_maps_enabled SET DEFAULT true;

Some good production notes here: 

https://github.com/danseely/cartodb-install/blob/master/PRODUCTION-DEPLOY.md

**Comment by chriswhong** [comment]
Hi, I'll make a note of this in the README as an additional step someone can take
