### ISSUE TITLE
widgets error?

### ISSUE THREAD

**Issue by anggorosantoso** [chriswhong/docker-cartodb#6]
The docker works with the (new) builder. But when I tried to add widget, it never show any result. Just the animated (query) bar, and then 'Refresh' button appears, with no result. Do you have the same issue? Thanks.

**Comment by anggorosantoso** [comment]
thank you so much @christianurich . will try this out and reporting here.

**Comment by chriswhong** [comment]
I think this is working in the latest version of the Dockerfile.  Thanks to @christianurich for the fix!
