### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by sandeepgadhwal** [chriswhong/docker-cartodb#7]
i installed it on a docker client but i am getting 404 error

**Comment by sandeepgadhwal** [comment]
please help me sir

**Comment by Namec** [comment]
you need to add manually the port 3000 to your browser url.

also the login page can be located at : YourIP:3000/login

**Comment by sandeepgadhwal** [comment]
sir the nginx config solved the problem

**Comment by sandeepgadhwal** [comment]
sir can we update the dockerised version of cartodb
